version: "3.9"
services:
  flutter:
    container_name: flutter-app
    build:
      context: .
      dockerfile: flutter.dockerfile
    working_dir: /project
    volumes:
      - ".:/project"
    ports:
      - "8090:8090"
      - "42000:42000"
    entrypoint: ./flutter-web.sh
